image: docker:19.03.2

stages:
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage : build
  script:
    -  chmod +x ./ci/build.sh && ./ci/build.sh
  retry: 2