image: docker:19.03.2

services:
  - docker:19.03.2-dind

stages:
  - test
  - prepare
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage : build
  script:
    - ci/build.sh
  retry: 2
  variables:
    TAG: TestTag